### PR TITLE
Overhaul stabilize

### PR DESCRIPTION
**Pull request by mjeveritt**
What a train-wreck that was!

This is the complete, fully signed-off, version. Finally.

### CODE REVIEW

**Comment by mjeveritt** [comment]
Ok this is now running on my test-bed .. will make sure it behaves well before approving for merge! :smiley_cat:

**Comment by mjeveritt** [comment]
@codeclimate - That's much better now - we'll see how testing goes.
Thanks for merging #84 @aliceinwire :smiley:

**Comment by aliceinwire** [comment]
news about this?

**Comment by mjeveritt** [comment]
From what I can tell - it's working better, but far from robust still.
I'd like to spend a bit more time examining the remaining failure modes, to weed these out.

I'm not sure whether this is the right function for it, or it needs renaming, but I'd also like to look at compile-and-boot testing the ebuild's side, as well as the raw sources+patches.

**Pull request merged**
